/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WidgetDropdown {
    'name': string;
  }
  interface WidgetDropdownAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'onOnToggle'?: (event: CustomEvent) => void;
  }

  interface CallbackWidget {
    'id': string;
    'isOpen': boolean;
    'isOpenChannels': boolean;
  }
  interface CallbackWidgetAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'isOpen'?: boolean;
    'isOpenChannels'?: boolean;
  }

  interface WidgetButton {
    'configs': any;
    'isOpenChannels': boolean;
  }
  interface WidgetButtonAttributes extends StencilHTMLAttributes {
    'configs'?: any;
    'isOpenChannels'?: boolean;
    'onOnOpenChannels'?: (event: CustomEvent) => void;
    'onOnOpenModal'?: (event: CustomEvent) => void;
  }

  interface WidgetModal {
    'configs': any;
  }
  interface WidgetModalAttributes extends StencilHTMLAttributes {
    'configs'?: any;
    'onOnCloseModal'?: (event: CustomEvent) => void;
  }

  interface WidgetPhone {}
  interface WidgetPhoneAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'WidgetDropdown': Components.WidgetDropdown;
    'CallbackWidget': Components.CallbackWidget;
    'WidgetButton': Components.WidgetButton;
    'WidgetModal': Components.WidgetModal;
    'WidgetPhone': Components.WidgetPhone;
  }

  interface StencilIntrinsicElements {
    'widget-dropdown': Components.WidgetDropdownAttributes;
    'callback-widget': Components.CallbackWidgetAttributes;
    'widget-button': Components.WidgetButtonAttributes;
    'widget-modal': Components.WidgetModalAttributes;
    'widget-phone': Components.WidgetPhoneAttributes;
  }


  interface HTMLWidgetDropdownElement extends Components.WidgetDropdown, HTMLStencilElement {}
  var HTMLWidgetDropdownElement: {
    prototype: HTMLWidgetDropdownElement;
    new (): HTMLWidgetDropdownElement;
  };

  interface HTMLCallbackWidgetElement extends Components.CallbackWidget, HTMLStencilElement {}
  var HTMLCallbackWidgetElement: {
    prototype: HTMLCallbackWidgetElement;
    new (): HTMLCallbackWidgetElement;
  };

  interface HTMLWidgetButtonElement extends Components.WidgetButton, HTMLStencilElement {}
  var HTMLWidgetButtonElement: {
    prototype: HTMLWidgetButtonElement;
    new (): HTMLWidgetButtonElement;
  };

  interface HTMLWidgetModalElement extends Components.WidgetModal, HTMLStencilElement {}
  var HTMLWidgetModalElement: {
    prototype: HTMLWidgetModalElement;
    new (): HTMLWidgetModalElement;
  };

  interface HTMLWidgetPhoneElement extends Components.WidgetPhone, HTMLStencilElement {}
  var HTMLWidgetPhoneElement: {
    prototype: HTMLWidgetPhoneElement;
    new (): HTMLWidgetPhoneElement;
  };

  interface HTMLElementTagNameMap {
    'widget-dropdown': HTMLWidgetDropdownElement
    'callback-widget': HTMLCallbackWidgetElement
    'widget-button': HTMLWidgetButtonElement
    'widget-modal': HTMLWidgetModalElement
    'widget-phone': HTMLWidgetPhoneElement
  }

  interface ElementTagNameMap {
    'widget-dropdown': HTMLWidgetDropdownElement;
    'callback-widget': HTMLCallbackWidgetElement;
    'widget-button': HTMLWidgetButtonElement;
    'widget-modal': HTMLWidgetModalElement;
    'widget-phone': HTMLWidgetPhoneElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
