/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CallbackWidget {
    'id': string;
    'isOpen': boolean;
  }
  interface CallbackWidgetAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'isOpen'?: boolean;
  }

  interface WidgetButton {
    'configs': any;
    'isOpenChannels': boolean;
  }
  interface WidgetButtonAttributes extends StencilHTMLAttributes {
    'configs'?: any;
    'isOpenChannels'?: boolean;
    'onOnOpenModal'?: (event: CustomEvent) => void;
  }

  interface WidgetModal {}
  interface WidgetModalAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'CallbackWidget': Components.CallbackWidget;
    'WidgetButton': Components.WidgetButton;
    'WidgetModal': Components.WidgetModal;
  }

  interface StencilIntrinsicElements {
    'callback-widget': Components.CallbackWidgetAttributes;
    'widget-button': Components.WidgetButtonAttributes;
    'widget-modal': Components.WidgetModalAttributes;
  }


  interface HTMLCallbackWidgetElement extends Components.CallbackWidget, HTMLStencilElement {}
  var HTMLCallbackWidgetElement: {
    prototype: HTMLCallbackWidgetElement;
    new (): HTMLCallbackWidgetElement;
  };

  interface HTMLWidgetButtonElement extends Components.WidgetButton, HTMLStencilElement {}
  var HTMLWidgetButtonElement: {
    prototype: HTMLWidgetButtonElement;
    new (): HTMLWidgetButtonElement;
  };

  interface HTMLWidgetModalElement extends Components.WidgetModal, HTMLStencilElement {}
  var HTMLWidgetModalElement: {
    prototype: HTMLWidgetModalElement;
    new (): HTMLWidgetModalElement;
  };

  interface HTMLElementTagNameMap {
    'callback-widget': HTMLCallbackWidgetElement
    'widget-button': HTMLWidgetButtonElement
    'widget-modal': HTMLWidgetModalElement
  }

  interface ElementTagNameMap {
    'callback-widget': HTMLCallbackWidgetElement;
    'widget-button': HTMLWidgetButtonElement;
    'widget-modal': HTMLWidgetModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
